version: '3.4'
services:
  flask:
    build: ./flask-devserver
    container_name: flask
    environment:
     - APP_NAME=MyFlaskApp
     - POSTGRES_USER=${POSTGRES_U}
     - POSTGRES_PASSWORD=${POSTGRES_PW}
     - POSTGRES_DB=${POSTGRES_DATABASE}
    ports:
     - "8080:8080"
    depends_on:
      db:
        condition: service_healthy


  k6:
    build: ./k6-loadtester
    depends_on:
      flask:
        condition: service_started
    environment:
      - K6_OUT=xk6-influxdb=http://influxdb:8086
      - K6_INFLUXDB_ORGANIZATION=application_loadtesting
      - K6_INFLUXDB_BUCKET=loadtest
      - K6_INFLUXDB_INSECURE=true
        # NOTE: This is an Admin token, it's not suggested to use this configuration in production.
        # Instead, use a Token with restricted privileges.
      - K6_INFLUXDB_TOKEN=EEKpryGZk8pVDXmIuy484BKUxM5jOEDv7YNoeNZUbsNbpbPbP6kK_qY9Zsyw7zNnlZ7pHG16FYzNaqwLMBUz8g==

  db:
    image: postgres:16.3-alpine
    restart: always
    container_name: postgresql
    environment:
      - POSTGRES_USER=${POSTGRES_U}
      - POSTGRES_PASSWORD=${POSTGRES_PW}
      - POSTGRES_DB=${POSTGRES_DATABASE}
      - PGPORT=8090
    expose:
      - '8090'
    volumes:
      - ./postgres-db/init.sql:/docker-entrypoint-initdb.d/create_tables.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_U} -d ${POSTGRES_DATABASE}"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
  
  influxdb:
    image: influxdb:2.7
    ports:
      - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - INFLUXDB_DB=k6
      - DOCKER_INFLUXDB_INIT_ORG=application_loadtesting
      - DOCKER_INFLUXDB_INIT_USERNAME=croco
      - DOCKER_INFLUXDB_INIT_PASSWORD=password1
      - DOCKER_INFLUXDB_INIT_BUCKET=loadtest
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=EEKpryGZk8pVDXmIuy484BKUxM5jOEDv7YNoeNZUbsNbpbPbP6kK_qY9Zsyw7zNnlZ7pHG16FYzNaqwLMBUz8g==


  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_BASIC_ENABLED=false